name: CI/CD

on:
  push:
    branches: [desenvolvimento]
  pull_request:
    branches: [main]

  workflow_dispatch: 

jobs:
  testes_unitarios:
    name: "Integração"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instalação de dependências
        run: pip install -r requirements.txt
      - name: Testes unitários
        run: pytest
  analise_estatica:
    name: "Bandit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instalando bandit
        run: pip install bandit
      - name: Análise estática
        run: bandit -r .
  analise_estatica_avancada:
    name: "SamGrep"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instalando SamGrep
        run: pip install semgrep
      - name: analise estatica avançada
        run: semgrep --config=auto .
  analise_dependencias:
    name: "Safety"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instalando Safety
        run: pip install safety
      - name: Analide de dependencias
        run: safety scan
